# Generated by Django 2.2.9 on 2020-02-18 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='served',
            field=models.BooleanField(default=False),
        ),
    ]
