# Generated by Django 2.2.9 on 2020-02-18 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_total_orders'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='total_orders',
            new_name='total_order',
        ),
    ]
