# Generated by Django 2.2.9 on 2020-02-19 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_cart_served_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='served_date',
            field=models.DateTimeField(),
        ),
    ]
